const shortcutActions = {
    "ctrl+alt+backspace": [EditorAPI.document.deleteChar],
    "ctrl+shift+a": [EditorAPI.dialog.toggleAccents],
    "ctrl+alt+shift+w": [EditorAPI.dialog.toggleWordCount],
    "ctrl+shift+l": [EditorAPI.document.format.alignLeft],
    "ctrl+shift+e": [EditorAPI.document.format.alignCenter],
    "ctrl+shift+r": [EditorAPI.document.format.alignRight],
    "ctrl+shift+j": [EditorAPI.document.format.alignJustify],
    "ctrl+b": [EditorAPI.document.format.boldText],
    "ctrl+i": [EditorAPI.document.format.italicizeText],
    "ctrl+u": [EditorAPI.document.format.underlineText],
    "alt+arrowright": [EditorAPI.navigation.selectLineEnd],
    "tab": [EditorAPI.document.insertTab],
    "enter": [EditorAPI.document.insertNewLine],
    "backspace": [EditorAPI.document.backspace],
    "arrowleft": [EditorAPI.navigation.selectCharLeft],
    "arrowright": [EditorAPI.navigation.selectCharRight],
    "arrowup": [EditorAPI.navigation.selectCharUp],
    "arrowdown": [EditorAPI.navigation.selectCharDown],
    "delete": [EditorAPI.document.deleteChar],
    " ": [EditorAPI.document.insertChar, ["&nbsp;"]]
}